### ISSUE TITLE
Pod role label cannot be switched correctly after kill leader pod

### ISSUE THREAD

**Issue by runkecheng** [radondb/xenondb#65]
## Operation recurrence 
The old leader is `test-xenondb-0`, the old follower is `test-xenondb-1` and `test-xenondb-2`.
### step 1
executes the script in leader node.
```
sysbench --db-driver=mysql --mysql-user=qingcloud --mysql-password=Qing@123 --mysql-host=<host> --mysql-port=<port> --mysql-db=qingcloud --range_size=100 --table_size=100000 --tables=4 --threads=128 --events=0 --time=3600 --rand-type=uniform /usr/share/sysbench/oltp_read_write.lua run
```
### step 2
delete the leader pod.
```
kubectl delete pod <leader-pod-name>
```
Then the leader pod automatically restarts and re-elects the leader after the restart is complete. but the label of the new leader pod is not updated.
```
kind: Pod
apiVersion: v1
metadata:
  name: test-xenondb-2
  generateName: test-xenondb-
  namespace: xenondb-deploy
  labels:
    app: test-xenondb
    controller-revision-hash: test-xenondb-5c8949f646
    release: test
    role: follower
    statefulset.kubernetes.io/pod-name: test-xenondb-2
```
## Log 
The IO status of the new leader node is `false`.
```
/ $ xenoncli cluster status
+-------------------------------------------------+--------------------------------+--------+---------+--------------------------+--------------------+----------------+-------------------------------------------------+
|                       ID                        |              Raft              | Mysqld | Monitor |          Backup          |       Mysql        | IO/SQL_RUNNING |                    MyLeader                     |
+-------------------------------------------------+--------------------------------+--------+---------+--------------------------+--------------------+----------------+-------------------------------------------------+
| test-xenondb-2.test-xenondb.xenondb-deploy:8801 | [ViewID:32 EpochID:2]@LEADER   | UNKNOW | OFF     | state:[NONE]␤            | [ALIVE] [READONLY] | [false/true]   | test-xenondb-2.test-xenondb.xenondb-deploy:8801 |
|                                                 |                                |        |         | LastError:               |                    |        |                                                 |
+-------------------------------------------------+--------------------------------+--------+---------+--------------------------+--------------------+----------------+-------------------------------------------------+
| test-xenondb-0.test-xenondb.xenondb-deploy:8801 | [ViewID:32 EpochID:2]@FOLLOWER | UNKNOW | OFF     | state:[NONE]␤            | [ALIVE] [READONLY] | [true/true]    | test-xenondb-2.test-xenondb.xenondb-deploy:8801 |
|                                                 |                                |        |         | LastError:               |                    |        |                                                 |
+-------------------------------------------------+--------------------------------+--------+---------+--------------------------+--------------------+----------------+-------------------------------------------------+
| test-xenondb-1.test-xenondb.xenondb-deploy:8801 | [ViewID:32 EpochID:2]@FOLLOWER | UNKNOW | OFF     | state:[NONE]␤            | [ALIVE] [READONLY] | [true/true]    | test-xenondb-2.test-xenondb.xenondb-deploy:8801 |
|                                                 |                                |        |         | LastError:               |                    |        |                                                 |
+-------------------------------------------------+--------------------------------+--------+---------+--------------------------+--------------------+----------------+-------------------------------------------------+
```

```
/ $ xenoncli cluster gtid
+-------------------------------------------------+----------+-------+--------------------------------------------------+------------------------------------------------------+
|                       ID                        |   Raft   | Mysql |                Executed_GTID_Set                 |                  Retrieved_GTID_Set                |
+-------------------------------------------------+----------+-------+--------------------------------------------------+------------------------------------------------------+
| test-xenondb-0.test-xenondb.xenondb-deploy:8801 | FOLLOWER | ALIVE | 17f2fb8e-f6af-4da1-b25a-09e1639d81e3:1-1079443,␤ |                |
|                                                 |          |       | 644c2d77-6b63-4843-a1ca-6d8bb45e448c:1-165432,␤  |                |
|                                                 |          |       | bc25fa13-b14a-4946-ac41-e4b2cec149e1:1-133170,␤  |                |
|                                                 |          |       | f3177eaf-2b0b-42cf-b6c0-7207a6e66ad4:1-159277    |                |
+-------------------------------------------------+----------+-------+--------------------------------------------------+------------------------------------------------------+
| test-xenondb-1.test-xenondb.xenondb-deploy:8801 | FOLLOWER | ALIVE | 17f2fb8e-f6af-4da1-b25a-09e1639d81e3:1-341721,␤  | 17f2fb8e-f6af-4da1-b25a-09e1639d81e3:255336-348183   |
|                                                 |          |       | 644c2d77-6b63-4843-a1ca-6d8bb45e448c:1-165432,␤  |                |
|                                                 |          |       | bc25fa13-b14a-4946-ac41-e4b2cec149e1:1-133170,␤  |                |
|                                                 |          |       | f3177eaf-2b0b-42cf-b6c0-7207a6e66ad4:1-159405    |                |
+-------------------------------------------------+----------+-------+--------------------------------------------------+------------------------------------------------------+
| test-xenondb-2.test-xenondb.xenondb-deploy:8801 | LEADER   | ALIVE | 17f2fb8e-f6af-4da1-b25a-09e1639d81e3:1-348183,␤  | 17f2fb8e-f6af-4da1-b25a-09e1639d81e3:1-1079443,␤     |
|                                                 |          |       | 644c2d77-6b63-4843-a1ca-6d8bb45e448c:1-165432,␤  | 644c2d77-6b63-4843-a1ca-6d8bb45e448c:141788-165432,␤ |
|                                                 |          |       | bc25fa13-b14a-4946-ac41-e4b2cec149e1:1-133170,␤  | bc25fa13-b14a-4946-ac41-e4b2cec149e1:84271-133170,␤  |
|                                                 |          |       | f3177eaf-2b0b-42cf-b6c0-7207a6e66ad4:1-159277    | f3177eaf-2b0b-42cf-b6c0-7207a6e66ad4:1-159277        |
+-------------------------------------------------+----------+-------+--------------------------------------------------+------------------------------------------------------+
```

```
mysql> show slave status\G
*************************** 1. row ***************************
               Slave_IO_State:
                  Master_Host: test-xenondb-0.test-xenondb.xenondb-deploy
                  Master_User: qc_repl
                  Master_Port: 3306
                Connect_Retry: 60
              Master_Log_File: mysql-bin.000006
          Read_Master_Log_Pos: 173547413
               Relay_Log_File: mysql-relay-bin.000004
                Relay_Log_Pos: 838635253
        Relay_Master_Log_File: mysql-bin.000004
             Slave_IO_Running: No
            Slave_SQL_Running: Yes
              Replicate_Do_DB:
          Replicate_Ignore_DB:
           Replicate_Do_Table:
       Replicate_Ignore_Table:
      Replicate_Wild_Do_Table:
  Replicate_Wild_Ignore_Table:
                   Last_Errno: 0
                   Last_Error:
                 Skip_Counter: 0
          Exec_Master_Log_Pos: 978983899
              Relay_Log_Space: 2180829427
              Until_Condition: None
               Until_Log_File:
                Until_Log_Pos: 0
           Master_SSL_Allowed: No
           Master_SSL_CA_File:
           Master_SSL_CA_Path:
              Master_SSL_Cert:
            Master_SSL_Cipher:
               Master_SSL_Key:
        Seconds_Behind_Master: 1148
Master_SSL_Verify_Server_Cert: No
                Last_IO_Errno: 2003
                Last_IO_Error: error reconnecting to master 'qc_repl@test-xenondb-0.test-xenondb.xenondb-deploy:3306' - retry-time: 60  retries: 1
               Last_SQL_Errno: 0
               Last_SQL_Error:
  Replicate_Ignore_Server_Ids:
             Master_Server_Id: 100
                  Master_UUID: 17f2fb8e-f6af-4da1-b25a-09e1639d81e3
             Master_Info_File: mysql.slave_master_info
                    SQL_Delay: 0
          SQL_Remaining_Delay: NULL
      Slave_SQL_Running_State: System lock
           Master_Retry_Count: 86400
                  Master_Bind:
      Last_IO_Error_Timestamp: 210425 10:05:06
     Last_SQL_Error_Timestamp:
               Master_SSL_Crl:
           Master_SSL_Crlpath:
           Retrieved_Gtid_Set: 17f2fb8e-f6af-4da1-b25a-09e1639d81e3:1-1079443,
644c2d77-6b63-4843-a1ca-6d8bb45e448c:141788-165432,
bc25fa13-b14a-4946-ac41-e4b2cec149e1:84271-133170,
f3177eaf-2b0b-42cf-b6c0-7207a6e66ad4:1-159277
            Executed_Gtid_Set: 17f2fb8e-f6af-4da1-b25a-09e1639d81e3:1-288523,
644c2d77-6b63-4843-a1ca-6d8bb45e448c:1-165432,
bc25fa13-b14a-4946-ac41-e4b2cec149e1:1-133170,
f3177eaf-2b0b-42cf-b6c0-7207a6e66ad4:1-159277
                Auto_Position: 1
         Replicate_Rewrite_DB:
                 Channel_Name:
           Master_TLS_Version:
```
The mysql log of `test-xenondb-2`.
```
2021-04-25T10:05:06.019869+08:00 157 [Note] Slave for channel '': received end packet from server due to dump thread being killed on master. Dump threads are killed for example during master shutdown, explicitly by a user, or when the master receives a binlog send request from a duplicate server UUID : Error

2021-04-25T10:05:06.020011+08:00 157 [Note] Slave I/O thread: Failed reading log event, reconnecting to retry, log 'mysql-bin.000006' at position 173547413 for channel ''

2021-04-25T10:05:06.020051+08:00 157 [Warning] Storing MySQL user name or password information in the master info repository is not secure and is therefore not recommended. Please consider using the USER and PASSWORD connection options for START SLAVE; see the 'START SLAVE Syntax' in the MySQL Manual for more information.

2021-04-25T10:05:06.021838+08:00 157 [ERROR] Slave I/O for channel '': error reconnecting to master 'qc_repl@test-xenondb-0.test-xenondb.xenondb-deploy:3306' - retry-time: 60 retries: 1, Error_code: 2003

2021-04-25T10:05:06.974288+08:00 157 [Note] Slave I/O thread killed during or after a reconnect done to recover from failed read

2021-04-25T10:05:06.974326+08:00 157 [Note] Slave I/O thread exiting for channel '', read up to log 'mysql-bin.000006', position 173547413

2021-04-25T10:05:12.311606+08:00 58170 [Note] Start binlog_dump to master_thread_id(58170) slave_server(101), pos(, 4)

2021-04-25T10:05:12.311651+08:00 58170 [Note] Start semi-sync binlog_dump to slave (server_id: 101), pos(, 4)

2021-04-25T10:05:16.989469+08:00 32 [Note] Semi-sync replication initialized for transactions.

2021-04-25T10:05:16.989546+08:00 32 [Note] Semi-sync replication enabled on the master.

2021-04-25T10:05:16.989841+08:00 0 [Note] Starting ack receiver thread

2021-04-25T10:06:10.012709+08:00 58194 [Note] Start binlog_dump to master_thread_id(58194) slave_server(100), pos(, 4)

2021-04-25T10:06:10.012747+08:00 58194 [Note] Start semi-sync binlog_dump to slave (server_id: 100), pos(, 4)

```
